version: '2'
services:
  jhipsterthird-mongodb:
    image: mongo:4.0.16
    ports:
      - '27017:27017'
    command: mongos --configdb jhipsterthird-mongodb-config
  jhipsterthird-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  jhipsterthird-mongodb-config:
    image: mongo:4.0.16
    container_name: jhipsterthird-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
